stages:
  - name: github-discover-repo
    type: exec
    skip_if_exists: "artifact://repo.txt"
    bind:
      repo: "artifact://repo.txt"
    options:
      cmds:
        - 'gh_discover_repo > "{repo}"'
