required-prompt: true

stages:
  - name: plan
    type: agent
    skip_if_exists: "artifact://plan.md"
    prompt:
      - "{{prompt}}"
    interpolation:
      instructions: "artifact://instructions.txt?"
    bind:
      plan: "artifact://plan.md"
    options:
      idle_timeout: 600

  - name: resolve-plan-source
    type: exec
    interpolation:
      plan: artifact://plan.md
    options:
      cmds:
        - 'gh_resolve_plan_source "{plan}" "{plan_source_issue_number}"'
    bind:
      plan_source_issue_number?: "artifact://plan-source-issue-number.txt"

  - name: publish-as-issue
    type: exec
    interpolation:
      plan: artifact://plan.md
    skip_if_exists: "artifact://plan-source-issue-number.txt"
    options:
      cmds:
        - 'gh_publish_issue "{plan}" > "{plan_issue_number}"'
    bind:
      plan_issue_number: "artifact://plan-issue-number.txt"

  - name: set-description
    type: exec
    interpolation:
      plan: artifact://plan.md
    bind:
      description?: "artifact://description.txt"
    options:
      cmds:
        - "head -1 \"{plan}\" | sed 's/^#\\+ *//' > \"{description}\""
